services:
  kong:
    image: kong
    container_name: kong
    volumes:
      - ./config:/usr/local/kong/declarative
      - ./custom-plugins:/usr/local/share/lua/5.1/kong/plugins
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: custom-auth   
    ports:
      - "8000:8000"
      - "127.0.0.1:7990:8001"
      - "8443:8443"
      - "127.0.0.1:8444:8444"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - expensestracker_arpanet

networks:
  expensestracker_arpanet:
    external: true
